### ISSUE TITLE
依赖的kaldi-native-fbank 项目如何编译arm64版本so文件

### ISSUE THREAD

**Issue by CrazyJson** [manyeyes/KaldiNativeFbankSharp#2]
我正在使用您的项目进行语音识别，感谢作者开源的项目。请问当前最新稳定版 1.1.2 依赖的kaldi-native-fbank对应版本是多少，大致的cmake步骤可以从哪里找到

**Comment by HarrickHeng** [comment]
same problem，how to solve it？

**Comment by CrazyJson** [comment]
you can use `dotnet add package Citms.KaldiNativeFbank-arm64 --version 1.1.2`

**Comment by HarrickHeng** [comment]
> you can use `dotnet add package Citms.KaldiNativeFbank-arm64 --version 1.1.2`

thx
